### ISSUE TITLE
Develop Item Table

### ISSUE THREAD

**Issue by seanlee10** [coska/2018.RestaurantPOS_Hall#3]
- Develop static header (column labels) and footer (subtotal, total, tax) 
- Use FlatList for dynamic item, populate 2 or 3 dummy items.

**Comment by nickyoon89** [comment]
- Used hard-coding data
- Couldn't make +, - buttons work
- Not sure how the "Discount" works, so I put 0 in it
- Put style one by one, so it became messy, should use custom components
